name: GitHub PR Format Checker
on:
  pull_request_target:
    types: [opened, ready_for_review]

jobs:
  title-check:
    runs-on: ubuntu-latest
    steps:
      - uses: naveenk1223/action-pr-title@master
        with:
          regex: ^TH-\d{4} .+$ # Regex the title should match. Should match the format: "TH-1234 Title"
          prefix_case_sensitive: false # title prefix are case insensitive